FirstTry/FirstTry/urls.py
from django.contrib import admin
from django.urls import path, include
from appone import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^appone/',include("appone.urls")),
    url(r'^$', views.index, name="index"),

]

FirstTry/appone/urls.py
from django.conf.urls import url
from appone import views

app_name = "appone"

urlpatterns = [
    url(r'^pics/$',views.pics, name = "pics"),
]

FirstTry/appone/models.py
from django.db import models

# Create your models here.

FirstTry/appone/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,"appone/index.html")

def pics(request):
    return render(request,"appone/pics.html")

FirstTry/templates/appone/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="C:\Users\pra115168\Documents\FirstTry\FirstTry\static\css\base.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appone:pics' %}">Pics</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    {%block body_block%}

    {%endblock%}


  </body>
</html>

FirstTry/templates/appone/index.html
{%extends "appone/base.html"%}

  {%block body_block%}

    <div class="container">
      <h1>Welcome to the indexpage</h1>
    </div>

  {%endblock%}

FirstTry/templates/appone/pics.html
{%extends "appone/base.html"%}

{%block body_block%}

<div class="container">
  <div class="card" style="width: 18rem;">
    <img src="C:\Users\pra115168\Documents\FirstTry\FirstTry\static\img\treehouse.jpg" class="card-img-top" alt="pic could not load">
    <div class="card-body">
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
</div>


{%endblock%}